FORMAT: 1A

# Module Project
REST API for module Project used for project based applications.

## Project [/projects/{id}]
Project is main container for application's data.

+ Model (application/json)

    + Body
    
            {
                "id": 1,
                "type": "Type of Project",
                "title": "Title of Project",
            }

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Project to perform action with. Has example value.


### Retrieve a Project [GET]
+ Response 200 (application/json)

    
            {
                "id": 1,
                "type": "Type of Project",
                "title": "Title of Project"
            }


### Update a Project [PUT]
+ Request (application/json)

        { "title": "Updated title of project" }
        
+ Response 200 (application/json)


    + Body
    
            {
                "id": 1,
                "title": "Updated title of project"
            }

    
### Remove a Project [DELETE]
+ Response 204

## Retrieve Project's parameters [/projects/{id}?params=true]
Retrieve project with parameters.

+ Model (application/json)

    + Body
    
            {
                "id": 1,
                "type": "Type of Project",
                "title": "Title of Project",
                "parameters": [
                    {
                        "name": "parameter 1",
                        "value": "abcd"
                    },
                    {
                        "name": "parameter 2",
                        "value": 123
                    }
                ]
            }

### Retrieve Project's parameters [GET]
If `params=true` in URL is not set, returns project without parameters.

+ Response 200
    [Retrieve Project's parameters][]


## Update Project's parameters [/projects/{id}/parameters]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Project.


### Update Project's parameters [PUT]
If parameter value contains `null` it will be removed.

+ Request

    + Body
    
                {
                    "parameters": [
                        {
                            "name": "parameter 1",
                            "value": "abcd"
                        },
                        {
                            "name": "parameter 2",
                            "value": null
                        }
                    ]
                }

+ Response 200
    + Body
    
                {
                    "parameters": [
                        {
                            "name": "parameter 1",
                            "value": "abcd"
                        }
                    ]
                }

## Projects Collection [/projects]
Collection of Projects.

+ Model (application/json)

    + Body
    
            [
                {
                    "id": 1,
                    "title": "Title of Project 1",
                    "parameters": [
                        {
                            "name": "parameter 1",
                            "value": "abcd"
                        },
                        {
                            "name": "parameter 2",
                            "value": 123
                        }
                    ]
                },
                {
                    "id": 2,
                    "title": "Title of Project 2",
                    "parameters": [
                        {
                            "name": "parameter 1",
                            "value": "abcd"
                        },
                        {
                            "name": "parameter 2",
                            "value": 123
                        }
                    ]
                }
            ]

### List all available Projects [GET]
+ Response 200 (application/json)

    [Projects Collection][]

### Create a Project [POST]
+ Request (application/json)

        {
            "id": 1,
            "type": "Type of Project",
            "title": "Title of Project"
        }

+ Response 201 (application/json)

    + Body
    
            {
                "id": 1,
                "title": "New project",
            }

